services:
  backend:
    image: kodakcms/mymusicapi:main
    env_file: mymusicapi-env
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
        #mongo:
        #condition: service_healthy       
    links:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: S3cureP@ssWord!
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 30
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: S3cureP@ssWord!

volumes:
  image2_storage: {}
